services:
  - type: web
    name: javaside
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SUPABASE_DB_URL
        sync: false
      - key: SUPABASE_DB_USER
        sync: false
      - key: SUPABASE_DB_PASSWORD
        sync: false
